# Generated by Django 5.0 on 2023-12-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='user',
        ),
        migrations.DeleteModel(
            name='CodeRecharge',
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
