# Generated by Django 5.0 on 2023-12-07 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NameServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_domaine', models.CharField(max_length=255, unique=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_expiration', models.DateField()),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('active', 'Active'), ('expire', 'Expiré')], default='en_attente', max_length=20)),
                ('ds_record', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nameservers', models.ManyToManyField(related_name='domaines', to='main.nameserver')),
            ],
        ),
    ]
